import pandas as pd
import talib

#  LOAD DATA
df = pd.read_csv("livedata_daywiselivedata2024.csv")
df['date'] = pd.to_datetime(df['date'])

for col in ['open', 'high', 'low', 'close']:
    df[col] = df[col].astype(float)

df = df.sort_values(['symbol', 'date'])

# FULL CANDLE LIST
CANDLE_FUNCS = {
    "CDL2CROWS": talib.CDL2CROWS,
    "CDL3BLACKCROWS": talib.CDL3BLACKCROWS,
    "CDL3INSIDE": talib.CDL3INSIDE,
    "CDL3LINESTRIKE": talib.CDL3LINESTRIKE,
    "CDL3STARSINSOUTH": talib.CDL3STARSINSOUTH,
    "CDL3WHITESOLDIERS": talib.CDL3WHITESOLDIERS,
    "CDLABANDONEDBABY": talib.CDLABANDONEDBABY,
    "CDLADVANCEBLOCK": talib.CDLADVANCEBLOCK,
    "CDLBELTHOLD": talib.CDLBELTHOLD,
    "CDLBREAKAWAY": talib.CDLBREAKAWAY,
    "CDLCLOSINGMARUBOZU": talib.CDLCLOSINGMARUBOZU,
    "CDLCONCEALBABYSWALL": talib.CDLCONCEALBABYSWALL,
    "CDLCOUNTERATTACK": talib.CDLCOUNTERATTACK,
    "CDLDARKCLOUDCOVER": talib.CDLDARKCLOUDCOVER,
    "CDLDOJI": talib.CDLDOJI,
    "CDLDOJISTAR": talib.CDLDOJISTAR,
    "CDLDRAGONFLYDOJI": talib.CDLDRAGONFLYDOJI,
    "CDLENGULFING": talib.CDLENGULFING,
    "CDLEVENINGDOJISTAR": talib.CDLEVENINGDOJISTAR,
    "CDLEVENINGSTAR": talib.CDLEVENINGSTAR,
    "CDLGAPSIDESIDEWHITE": talib.CDLGAPSIDESIDEWHITE,
    "CDLGRAVESTONEDOJI": talib.CDLGRAVESTONEDOJI,
    "CDLHAMMER": talib.CDLHAMMER,
    "CDLHANGINGMAN": talib.CDLHANGINGMAN,
    "CDLHARAMI": talib.CDLHARAMI,
    "CDLHARAMICROSS": talib.CDLHARAMICROSS,
    "CDLHIGHWAVE": talib.CDLHIGHWAVE,
    "CDLHIKKAKE": talib.CDLHIKKAKE,
    "CDLHIKKAKEMOD": talib.CDLHIKKAKEMOD,
    "CDLHOMINGPIGEON": talib.CDLHOMINGPIGEON,
    "CDLIDENTICAL3CROWS": talib.CDLIDENTICAL3CROWS,
    "CDLINNECK": talib.CDLINNECK,
    "CDLINVERTEDHAMMER": talib.CDLINVERTEDHAMMER,
    "CDLKICKING": talib.CDLKICKING,
    "CDLKICKINGBYLENGTH": talib.CDLKICKINGBYLENGTH,
    "CDLLADDERBOTTOM": talib.CDLLADDERBOTTOM,
    "CDLLONGLEGGEDDOJI": talib.CDLLONGLEGGEDDOJI,
    "CDLLONGLINE": talib.CDLLONGLINE,
    "CDLMARUBOZU": talib.CDLMARUBOZU,
    "CDLMATCHINGLOW": talib.CDLMATCHINGLOW,
    "CDLMATHOLD": talib.CDLMATHOLD,
    "CDLMORNINGDOJISTAR": talib.CDLMORNINGDOJISTAR,
    "CDLMORNINGSTAR": talib.CDLMORNINGSTAR,
    "CDLONNECK": talib.CDLONNECK,
    "CDLPIERCING": talib.CDLPIERCING,
    "CDLRICKSHAWMAN": talib.CDLRICKSHAWMAN,
    "CDLRISEFALL3METHODS": talib.CDLRISEFALL3METHODS,
    "CDLSEPARATINGLINES": talib.CDLSEPARATINGLINES,
    "CDLSHOOTINGSTAR": talib.CDLSHOOTINGSTAR,
    "CDLSHORTLINE": talib.CDLSHORTLINE,
    "CDLSPINNINGTOP": talib.CDLSPINNINGTOP,
    "CDLSTALLEDPATTERN": talib.CDLSTALLEDPATTERN,
    "CDLSTICKSANDWICH": talib.CDLSTICKSANDWICH,
    "CDLTAKURI": talib.CDLTAKURI,
    "CDLTASUKIGAP": talib.CDLTASUKIGAP,
    "CDLTHRUSTING": talib.CDLTHRUSTING,
    "CDLTRISTAR": talib.CDLTRISTAR,
    "CDLUNIQUE3RIVER": talib.CDLUNIQUE3RIVER,
    "CDLUPSIDEGAP2CROWS": talib.CDLUPSIDEGAP2CROWS,
    "CDLXSIDEGAP3METHODS": talib.CDLXSIDEGAP3METHODS
}

# APPLY PER SYMBOL
def apply_candles(group):
    o, h, l, c = group['open'], group['high'], group['low'], group['close']
    for name, func in CANDLE_FUNCS.items():
        group[name] = func(o, h, l, c)
    return group

df = df.groupby('symbol', group_keys=False).apply(apply_candles)

# SAVE ALL VALUES
df.to_csv("all_candlestick_values_full_history.csv", index=False)

print("✅ All candlestick values saved (full history)")
